### ISSUE TITLE
SerpAPI raises a 429 when plan limit is reached

### ISSUE THREAD

**Issue by mspronesti** [serpapi/serpapi-python#16]
Is there a reason why SerpAPI raises a 429 error when the plan limit is reached?  

```py
serpapi.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://serpapi.com/search?engine=google_scholar&q=MY_QUERY&api_key=MY_API_KEY
```

I expected to either get "Error" when accessing the `search_metadata.status` field of the retrieved JSON (as mentioned in the [docs](https://serpapi.com/google-scholar-api#api-results)) or at least a meaningful exception.

**Comment by hilmanski** [comment]
Hi, @mspronesti, thank you very much for opening the issue. We believe 429 is the correct HTTP status code to send when handling too many requests. 

Reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429

We still appreciate your input and might change this if many customers find that's better. Please let us know if you need anything else.

**Comment by mspronesti** [comment]
Hi @hilmanski, thanks for your reply. Could you elaborate a little more on why 429 is appropriate in this case? I am only sending 1 request using a valid API key with no more searches left (not the account request rate per unit of time).

**Comment by hilmanski** [comment]
I can see how it can be confusing. We offered different plans based on the search credits. So, in a way, we limit how many requests you can perform in a month. It's aligned with the explanation here:

> The HTTP 429 Too Many Requests [client error response](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#client_error_responses) status code indicates the client has sent too many requests in a given amount of time

I hope it makes sense.
